export const NUMBER_OF_INPUT_NODES = 2;
export const NUMBER_OF_OUTPUT_NODES = 2;

export const PROBABILITY_TO_ADD_CONNECTION = 0.2;
export const PROBABILITY_TO_ADD_NODE = 0.3;
export const PROBABILITY_TO_SHIFT_WEIGTH = 0.1;
export const PROBABILITY_TO_RANDOM_WEIGHT = 0.125;
export const PROBABILITY_TO_TOGGLE_CONNECTION = 0.05;

export const WEIGHT_SHIFT_STRENGTH = 0.3;
export const WEIGHT_RANDOM_STRENGTH = 0.01;
